language: node_js
node_js:
- v6
- v7
before_install: npm install -g codecov
after_success:
- codecov -e TRAVIS_NODE_VERSION
deploy:
  provider: npm
  email: hourliert@gmail.com
  api_key:
    secure: FsPIDBzyObxm51PzJzjl3dyyYFgG60GhVaaCJwvOCnLAVENy7Ns7CjAud2wd3WpGpvlmvi9glgvziZEI6oqgpQsG8/QC/CISVT/Rpi3c4BuOl96xpE0AVr/S/3V9/YSnlL/uAZQo57zp+O9Us4et8vnSW9UL6feSzawrIGf+i4ur4g+2kMEmXX2zpZhQHWFWMpz8nAM5EnlbZs+FK+zybCbsymV4IS4izkreToOoAddxD70mleMxQFTVWqIcGAk23hPwvXh/ZAQDO5EIi2a0EgjGo9GCWppTf8keK9GEixbyD6nW8+Mjze6VnYv9nxzXGtV1BRWTCuTCUhIg1xZV44tsnJL7UN1DiyDF1iWgA4+dZkWGRvJtXO7c22M/7Juicz1sZdWD0xOQ3EQE6bhU6lxR0dp/cDqKlGkRbWM3OYzFXDgI1OS6p8lhvLFzaXpbaljn6giY2PwLj/r5mxAsWsGdI6NYskD8mQtDwffzb6JdidFb5fpIkdd0cxQIt8SNZZT5T2hEcNllc0GoAe/FhwiMwhTDD9rhzdCsSlwg6Av/dA5DQZ6M41U8dCJ7x/v4AiSFxw7QELC+36lXcmyY3jUDvP+35xBXfwbrPeB2zv3X/2m0aAlNzzOaOrjwh4OTlQJODBRwoYndxD9rq8CpbYUJSzFSZ8kuDC9Kn5Sj0+c=
  on:
    tags: true
    repo: FoodMeUp/redux-rac-utils
