language: node_js
node_js:
- v6
- v7
before_install: npm install -g codecov
after_success:
- codecov -e TRAVIS_NODE_VERSION
deploy:
  skip_cleanup: true
  provider: npm
  email: hourliert@gmail.com
  api_key:
    secure: n2EAntvzU5nBnpYoU+NKJhN8BS8bOD/lASESmrckrywFYhVQn2VHKA/BShCXo6149ATObdynTesn+Pl2fPmd+j1PpjU4dXrG+DzQp+mzEp9ccipnWGdvIKdKxbzAGJjmLed1SXfwrq3S7QBAMAKsYT/gQec1m5/Vt9E0jTJwq/Zi4iqL3c0My7BjWT+lhU4fng7Fc/7h+J5hO13jtDqYQYbczB/AmCu0dqAnwMEbswis3YDTPdiyO+nYGOYHmKo6nH5WNoL3OmDkgf9gb0b9+Yf+rKmXTDAM/oIHM1rENcAtZxsDOZSYN0AKykkEJL6mjrvnCzjBPGaZe/TqfLXlMdG5fnj7yJ86KTC7B258fJymsqd4dJoBSaQeOQKENmgDyP4tFryN4DOHa8u5DWzw2ma+qWmPIYIHIntkUJyDCKOM2ITXuwjUoQui76hFxBX/XruJZzsjCHoJo8edu0E1Z0pkB8PG3vHw46LZXt0IpP4PI5LEV5YtP9Jga5nkIMadD6abynyUiJCUsjKRQi+7+vGZ9fLs8lYcAS9erhnffs3bByNM0CdQhVFKPpaYEEmepNyKO9lBYmLCY4yVbVxMrDV0sIyKZLhGS8rS5WFcQDmv4Kyqc7oC2P9/tkNg/ggdfgKsw62o6h5lzwLLKpmzY9I/beYP1ahJEiIVfmrGVa0=
  on:
    tags: true
    repo: FoodMeUp/redux-rac-utils
